examples/dev-server-fargate/main.tf
test/acceptance/setup-terraform/main.tf

Use only availability zones

---

examples/dev-server-fargate/README.md

A few fixes and a clarification that the Consul UI might also come up after a few minutes.

A couple of README fixes and clarifications

---

examples/dev-server-ec2/bastion/bastion.tf
examples/dev-server-ec2/ecs-cluster.tf

Lookup AMI IDs rather than hardcoding in EC2 example

---

examples/dev-server-ec2/ecs-cluster.tf

Hello,
I found one spelling error. Project is awesome so far! Thanks for all you do.

updated spelling of ecs in ecs-cluster.tf

---

examples/dev-server-ec2/ecs-cluster.tf

Correct other ecs spelling

---

CHANGELOG.md

Set 0.2.0 version in changelog

Set 0.2.0 version in changelog

---

examples/dev-server-fargate/main.tf

Update dev-server-fargate example with health checks
Manually ran this locally.
👀 

dev-server-fargate: Update example with health checks

---

CHANGELOG.md
modules/acl-controller/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf

Prep 0.3.0 release

---

modules/mesh-task/main.tf

Open development for next version
👀 
👀 

Set version to 0.3.0-dev

---

modules/acl-controller/variables.tf
modules/mesh-task/iam.tf
modules/mesh-task/main.tf
modules/mesh-task/templates/consul_client_command.tpl
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/pass-app-entrypoint/main.tf

- Remove markdown that doesn't render for modules in the Terraform registry.
- Avoid `default = null` for optional variables.
- [Preview with a personal test module](https://registry.terraform.io/modules/pglass/testmodule/pglass/latest/submodules/mesh-task?tab=inputs). 
- I copied the `variables.tf` files to a [test repo](https://github.com/pglass/terraform-pglass-testmodule) in order to preview the docs in the TF registry.
- Acceptance tests
- Double check logic changes for non-null default values

Improve Terraform Registry documentation

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
modules/acl-controller/variables.tf
modules/dev-server/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf

* Bump `consul-ecs` image to `0.4.0`
* Bump `consul` image to `1.11.4`
* Bump `envoy` image to `1.20.2`
👀 

Prepare 0.4.0 release

---

modules/mesh-task/main.tf

Set version to 0.4.0-dev

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
modules/acl-controller/variables.tf
modules/mesh-task/variables.tf

- Patch release to fix bug in secret name when admin partitions are not enabled.
- New acceptance test added to the basic install tests.
:eyes:

release 0.4.1

---

modules/mesh-task/main.tf

- Reset version string to dev version
:eyes: 
:eyes: 

reset to dev version

---

modules/mesh-task/main.tf

Set the version back to 0.5.0-dev after the release

Set version back to dev

---

CHANGELOG.md

This merges the release notes for 0.5.0-beta1 and 0.5.0 together for clarity.
👀 

Merge 0.5.0-beta1 release notes into 0.5.0

---

CHANGELOG.md

This adds the 0.4.2 entry to the changelog on main.

Add 0.4.2 to changelog

---

.circleci/config.yml
test/acceptance/tests/basic/basic_test.go

* Bump the VM size, since past runs are maxing out CPU and memory ([example](https://app.circleci.com/pipelines/github/hashicorp/terraform-aws-consul-ecs/793/workflows/44bbceb2-54d9-4cc1-9324-67a0473ec939/jobs/2865/resources), [example](https://app.circleci.com/pipelines/github/hashicorp/terraform-aws-consul-ecs/793/workflows/44bbceb2-54d9-4cc1-9324-67a0473ec939/jobs/2866/resources), [example](https://app.circleci.com/pipelines/github/hashicorp/terraform-aws-consul-ecs/790/workflows/763f6fe3-470c-4f4b-b088-00ffaf61d894/jobs/2857/resources), [example](https://app.circleci.com/pipelines/github/hashicorp/terraform-aws-consul-ecs/790/workflows/763f6fe3-470c-4f4b-b088-00ffaf61d894/jobs/2858/resources))
* Fix a missing bounds check in a test assertion, since container logs could be temporarily …

Fix acceptance tests

---

.circleci/config.yml
modules/dev-server/consul_1_14_compat.tf
modules/dev-server/main.tf
test/acceptance/framework/config/config.go
test/acceptance/framework/helpers/cloudwatch.go
test/acceptance/setup-terraform/hcp/main.tf
test/acceptance/setup-terraform/hcp/variables.tf
test/acceptance/setup-terraform/main.tf
test/acceptance/setup-terraform/outputs.tf
test/acceptance/setup-terraform/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/hcp/hcp_test.go
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf

Update the acceptance tests and CI jobs to test with Consul 1.13 and 1.14.

Test with Consul 1.13 and 1.14

---

.copywrite.hcl

- Adding the copywrite.hcl file to automate copyright headers
- clone repo
- brew install copywrite 
- In the root directory of the repo
```
copywrite headers 
```

Added copywrite setup file

---

.github/workflows/terraform-ci.yml
CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/setup-terraform/main.tf

- Includes commits from the following PRs
#185 
#186 
#187 
CI

Manual backport for bumping Consul and Envoy versions

---

examples/service-sameness/variables.tf

Fix ECS image to use the official dev image

---

modules/gateway-task/main.tf
modules/gateway-task/variables.tf
test/acceptance/tests/validation/terraform/mesh-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Cherry-picked the changes from #210 
CI

Expose `gateway_count` in gateway module (#210)

---

examples/admin-partitions/terraform/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf

- Change image versions to use the release candidate images
CI

Bump Consul & Consul dataplane image versions

---

examples/admin-partitions/terraform/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf

Bump Consul dataplane image version (#216)

---

examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

Point terraform modules to use latest Consul images (#221)

---

examples/service-sameness/README.md

- Fix broken images and point them to absolute paths

Fix broken image links

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Update image versions in the main branch
- Update the CHANGELOG

Update image versions

---

.github/workflows/terraform-ci.yml
CHANGELOG.md
modules/gateway-task/main.tf
modules/mesh-task/main.tf
test/acceptance/framework/config/config.go
test/acceptance/framework/flags/flags.go
test/acceptance/setup-terraform/outputs.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/main.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

Fix flaky acceptance tests

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
examples/admin-partitions/terraform/hcp_consul.tf
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Uses the 0.7.1 consul-ecs dev image for all the modules/examples
- Bump Consul version to 1.17.1

Prepare 0.7.1 release

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

- Prepare dev version for 0.7.2

Prepare dev mode for 0.7.2

---

.github/workflows/nightly-ecs-examples-validator.yml
examples/terminating-gateway/outputs.tf
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/api-gateway/main.go
test/acceptance/examples/scenarios/common/fake_service.go
test/acceptance/examples/scenarios/terminating-gateway/main.go

- Added tests to test usage of API and terminating gateways
- Add both of them as a separate job in the CI pipeline

Scenario tests to cover gateways

---

.github/workflows/nightly-ecs-examples-validator.yml
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/ec2-tproxy/main.go

- Added a scenario test for the EC2 TProxy terraform example

Add scenario test for EC2 TProxy

---

test/acceptance/examples/scenarios/service-sameness/main.go

- Fixes a small bug for validating sameness groups in the 0.7.x branch

Fix sameness group validation bug

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

Bring back dev version for terraform modules

---

.github/workflows/nightly-ecs-examples-validator.yml
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/terminating-gateway-tproxy/main.go

- Link for a successful run of the scenario https://github.com/hashicorp/terraform-aws-consul-ecs/actions/runs/7725177577/job/21058875191

Add scenario test for TGW with TProxy

---

examples/api-gateway/gateway.tf
examples/cluster-peering/gateway/gateway.tf
examples/mesh-gateways/gateway/gateway.tf
examples/service-sameness/gateway/gateway.tf
examples/terminating-gateway/gateway.tf

- Manual backport of https://github.com/hashicorp/terraform-aws-consul-ecs/pull/285

[0.8.0-rc1] - Fix Tproxy related inputs for examples (#285)

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Bump Consul-ECS images to point to 0.7.3
- Updated CHANGELOG

Prepare 0.7.3 prod release

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

Bring back dev version for 0.6.x

---

CHANGELOG.md

Consolidate CHANGELOG for latest releases

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

Bring back dev version for 0.7.x

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

- Similar to https://github.com/hashicorp/terraform-aws-consul-ecs/pull/267 but adding the relevant changes into main.

Reduce health check interval to improve bootstrap time

---

modules/gateway-task/main.tf
modules/mesh-task/main.tf

- Making this change because the release branch has already been cut off of main

Bump modules to 0.9.0-dev

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/datacenter/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
examples/terminating-gateway-tls/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf
test/acceptance/tests/tproxy/terraform/main.tf

- Update Consul to 1.18.0
- Update Consul dataplane to 1.4.0
- Update Consul ECS to 0.8.0

Prepare 0.8.0 release

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/datacenter/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
examples/terminating-gateway-tls/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf
test/acceptance/tests/tproxy/terraform/main.tf

- Stage 0.8.1 release changes.

build: prepare for 0.8.1 release

---

.github/CODEOWNERS

NO_JIRA: Update CODEOWNERS
