README.md
modules/mesh-task/main.tf

Indicate which container is leveraging [`consul-ecs`](https://github.com/hashicorp/consul-ecs)
* running `terraform plan` after this change shows replacements where expected
* `terraform apply` succeeds, test server and app visible

Update mesh task container name

---

.circleci/config.yml
test/acceptance/README.md
test/acceptance/framework/config/config.go
test/acceptance/framework/flags/flags.go
test/acceptance/framework/suite/suite.go
test/acceptance/setup-terraform/outputs.tf
test/acceptance/tests/basic/basic_test.go

Since we use `setup-terraform` template to set up our acceptance tests, I thought it'd be nice if tests just took the output of that terraform and parsed them into the test config. This makes running tests locally much easier. Let me know what you think!
This PR also adds a few other minor changes:
- Skip cleanup if both `-no-cleanup-on-failure` is set and if test has failed.
- Removes `-suffix` flag. We were no longer using it after the change to generate random ids for each test in #19

Use output from setup-terraform by default to create config to run acceptance tests

---

.circleci/config.yml
examples/dev-server-ec2/main.tf
examples/dev-server-fargate/main.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/docker/Test.dockerfile

* Add a `Test.dockerfile` to build the `consul-ecs-test` image. I manually built and pushed `hashicorpdev/consul-ecs-test:0.2.0`
* Switch to HashiCorp mirror URLs
* Tidy the Circle CI config

"Proper" CI images

---

CHANGELOG.md
modules/acl-controller/variables.tf
modules/mesh-task/variables.tf

- Update the changelog for the 0.2.0-beta2 release
- Update the default docker images for the acl controller and mesh task to the 0.2.0-beta2 one
On CI

Update the changelog + docker image for the 0.2.0-beta2 release

---

CHANGELOG.md
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/framework/config/config.go
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf

- Add `service_tags`, `service_meta` and `service_name` input variables to the mesh-task. When `service_name` is set, it is used as the Consul service name rather than the ECS task's family name in the mesh-init container, the health-sync container and the ACL controller.
Tests
👁️

Add the Ability to Set More Consul Service Fields

---

CHANGELOG.md
examples/dev-server-ec2/main.tf
examples/dev-server-fargate/main.tf
modules/mesh-task/templates/consul_client_command.tpl
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/acl-secret-name-prefix-validate/main.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/basic/terraform/ca-cert-validate/main.tf
test/acceptance/tests/basic/terraform/consul-client-token-validate/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf

- modules/mesh-task: The `retry_join`variable was updated to take a list of members rather than a single member. This is a breaking change.
- I tried these changes out with [a "standard" tier deployment](https://github.com/hashicorp/terraform-aws-consul-ecs/commit/89ae81e659185477937af5b67ce134ddb0816731) and confirmed that the tests pass. A standard tier deployment runs on three nodes.
👀

Support Multiple Consul Nodes with `retry_join`

---

CHANGELOG.md
modules/acl-controller/main.tf
modules/mesh-task/main.tf

Since the ACL-controller/mesh task rely on deterministic secret names, we need the ability to delete a secret and then recreate it. Without this change deleting and recreating a secrete got this error: "Error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion."
With the ACLs enabled:
1. Create a mesh task service
2. Delete a mesh task service
3. Recreate the mesh task service
👁️

Fix a secrets manager deletion and recreation bug

---

examples/dev-server-ec2/main.tf
examples/dev-server-fargate/main.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/volume-variable/main.tf

- Add a `volumes` variable to mesh-task so that users can define additional volumes for the ECS task
Unit test included
👀 

Allow passing volumes into mesh-task

---

test/acceptance/tests/basic/terraform/volume-variable/main.tf

- Fix test that broke now that `retry_join` accepts an array of strings
CI
👁️

Fix test that broke now that `retry_join` accepts an array of strings

---

.circleci/config.yml
.gitignore
test/acceptance/framework/helpers/cloudwatch.go
test/acceptance/tests/basic/basic_test.go
test/docker/Test.dockerfile

Simplify grabbing Cloud Watch logs by using the ecs-cli (split off from https://github.com/hashicorp/terraform-aws-consul-ecs/pull/60 which was following up on some PR comments)
👀 

tests: Use ecs-cli to grab logs

---

CHANGELOG.md
modules/acl-controller/main.tf
modules/acl-controller/variables.tf

Add [`assign_public_ip`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#assign_public_ip) to ACL controller, which is passed through to the ECS service.
Manually:
- Create VPC with public subnets only
- Run the dev-server in secure config with `assign_public_ip = true`
- Run the consul-acl-controller with `assign_public_ip = true`
- Validate the ACL controller service shows `Auto-assign public IP   ENABLED` ![Screen Shot 2021-11-11 at 2 34 04 PM](https://user-images.githubusercontent.com/1077740/141365200-26d06082-b2f0-4f0d-bee4-111b5713c803.png)
- Validate the ACL controller was able to start and is assigned a public ip: ![Screen Shot 2021-11-11 at 2 36 35 PM](https://user-images.githubusercontent.com/1077740/141365498-367f6828-4892-4069-ac53-8fb8c …

Allow assigning public ip to ACL controller task

---

CHANGELOG.md
modules/mesh-task/iam.tf
modules/mesh-task/main.tf
modules/mesh-task/outputs.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/basic/terraform/pass-existing-iam-roles/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf

* Add `task_role_arn` and `execution_role_arn` variables to allow users to pass in an IAM role. If not provide, they are created.
* No longer add SSM permissions by default
👀 

Allow passing in IAM roles to mesh-task

---

modules/dev-server/main.tf

Closes #74
- Creates another security group to explicitly attach to ecs service for consul dev server when using load balancer
- Minor name convention changes to security groups
- Tested the changes in my own project
- Attempted to run the test detailed at the [test directory](https://github.com/hashicorp/terraform-aws-consul-ecs/tree/main/test/acceptance) of the project, but it was excessive and the final status was unclear.
- **Note**: this required sessionmanager cli from aws which is undocumented in the Readme
- The test command attempts to run HCP tests which I don't have configured and which is run last and the only thing reported at the end. Perhaps a maintainer can run this test to confirm.
[Changelog …

Add ecs security group allowing traffic from load balancer

---

examples/dev-server-ec2/consul-server.tf
examples/dev-server-fargate/consul-server.tf
modules/dev-server/main.tf
modules/dev-server/outputs.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf

In #75, the dev-server was restricted to only allow access from the load balancer. In our examples, mesh-tasks use the default security group, so this ensures they can access the dev-server.
(Acceptance tests were not affected because they do not configure a load balancer for the dev-server)
* Deployed the `dev-server-fargate` and `dev-server-ec2` examples, and checked services register and the application is working
👀 

Fix dev-server examples

---

examples/dev-server-fargate/main.tf
modules/dev-server/main.tf
modules/mesh-task/config.tf
modules/mesh-task/main.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf

Update mesh-task to support file-based config for consul-ecs (mesh-init, health-sync).
See https://github.com/hashicorp/consul-ecs/pull/53
Acceptance tests, and ran the dev-server-fargate example.

File-based config for consul-ecs

---

CHANGELOG.md
modules/mesh-task/main.tf

* Remove port mappings that are not needed in `awsvpc` networking mode since Consul and Envoy bind to the interface of the Task ENI for gossip and the public listener port, respectively.
* Acceptance tests
:eyes:

mesh-task: Remove unnecessary port mappings

---

test/docker/Test.dockerfile

- Swap out `circleci/golang` image with `cimg/go` in the CircleCI configuration.
The tests still pass
👁️

 Swap out circleci/golang with cimg/go now that circleci/golang is deprecated

---

modules/mesh-task/config.tf

- Simplify config to correspond with https://github.com/hashicorp/consul-ecs/pull/54 which allows null/optional values

mesh-task: Leverage optional values to simplify config

---

CHANGELOG.md
modules/mesh-task/main.tf
modules/mesh-task/templates/consul_agent_defaults.hcl.tpl
modules/mesh-task/templates/consul_client_command.tpl
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf

* Add a `consul_agent_configuration` variable to support passing an additional config file to the Consul agent.
Acceptance tests, and also ran the example with additional Consul config

Support passing Consul Agent configuration

---

modules/mesh-task/main.tf

Add the following new tags to the task definition:
* `consul.hashicorp.com/module = "terraform-aws-consul-ecs"`
* `consul.hashicorp.com/module-version = "x.y.z-dev"`
Ran the dev-server-fargate example, and checked the tags:
👀 

mesh-task: Include module + module-version tags

---

CHANGELOG.md
modules/acl-controller/main.tf
modules/acl-controller/variables.tf

Support `security_groups` input variable for ACL controller
Fixes #88 
👀 

Support passing security groups to ACL controller

---

CHANGELOG.md
modules/mesh-task/main.tf
modules/mesh-task/validation.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/admin-partition-validate/main.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf

- Set secret name correctly when partition and namespace are present.
- Add validation for partition and namespace variables.
- Add acceptance tests for updates.
- Ran the acceptance tests
:eyes:

Correct secret name when admin partitions are enabled

---

modules/mesh-task/main.tf

This sets `initProcessEnabled` on each of the injected containers to see if this helps with execute-command reliability.
From [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-enabling-and-using),
> If you set the task definition parameter initProcessEnabled to true, this starts the init process inside the container, which removes any zombie SSM agent child processes found. The following provides an example.
Not really sure, but both consul-client and mesh-init start at the beginning of the task, so maybe we're getting different behavior depending on which starts first?
👀 

Set initProcessEnabled on injected containers

---

CHANGELOG.md
modules/dev-server/main.tf
modules/dev-server/outputs.tf
modules/dev-server/variables.tf

- Add `consul_license` input variable to specify an enterprise license key. This is placed in a Secrets Manager secret that is the set as the `CONSUL_LICENSE` variable for the dev-server
- Add `wait_for_steady_state` input variable, which is passed through to the ECS service
- Add `bootstrap_token_id` output variable
Manually
👀 

dev-server: Support Consul enterprise license

---

.circleci/config.yml
CHANGELOG.md
modules/acl-controller/main.tf
modules/acl-controller/variables.tf
modules/dev-server/variables.tf
modules/mesh-task/config.tf
modules/mesh-task/iam.tf
modules/mesh-task/main.tf
modules/mesh-task/outputs.tf
modules/mesh-task/templates/consul_agent_defaults.hcl.tpl
modules/mesh-task/templates/consul_client_command.tpl
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf

This is an incremental change which flags off the login functionality until the auth method is fully supported. By default, the old mechanism for tokens is used (secrets in Secrets Manager). The `client_token_auth_method_name`, `service_token_auth_method_name`, and `consul_http_addr` variables are required to be set to use the new mechanism which logs in to auth method. Later, we'll switch over to the auth method as the default for ACL tokens.
- The server CA cert file is now placed on the shared volume, `/consul/consul-ca-cert.pem`, so that mesh-init has access to the file for its `consul login`
- New input variables: `client_token_auth_method_name`, `service_token_auth_method_name`, and `consul_http_addr`
- The IAM task role is configured with an `iam:GetRole` permission for itself
- …

Support the auth method

---

modules/mesh-task/templates/consul_client_command.tpl

Copy the approach from https://github.com/hashicorp/consul-k8s/pull/887 for dealing with inherent token replication lag.
See: https://github.com/hashicorp/consul-ecs/pull/79
👀 

Mitigate against token replication lag

---

examples/dev-server-ec2/main.tf
examples/dev-server-fargate/main.tf

This endpoint returns OK even if the upstream services are down.
This ensures the ALB won't cause the task to be stopped if its upstream
instances are having issues.
- local testing

Use /health endpoint for fake-service

---

CHANGELOG.md
modules/dev-server/main.tf

```
│ Warning: Argument is deprecated
│
│   with module.dev_consul_server.tls_self_signed_cert.ca,
│   on ../../modules/dev-server/main.tf line 20, in resource "tls_self_signed_cert" "ca":
│   20:   key_algorithm   = "ECDSA"
│
│ This is now ignored, as the key algorithm is inferred from the `private_key_pem`.
╵
```
- applied
- code

Remove deprecated field

---

examples/admin-partitions/README.md
examples/dev-server-ec2/README.md
examples/dev-server-fargate/README.md

When we do our next release we need to update these checkout commands so that
users will use a tagged version of our examples, not main.

Placeholder for checking out tag in examples

---

CHANGELOG.md
modules/mesh-task/main.tf
modules/mesh-task/templates/consul_client_command.tpl
test/acceptance/tests/basic/basic_test.go

This updates mesh-task to run `health-sync` whenever ACLs are enabled, so that it can do a `consul logout` when the task stops. The permissions of the `/consul/client-token` are changed in order to be readable by the `consul-ecs` user in the health-sync container.
- Acceptance tests

Ensure health-sync runs, to do consul logout

---

modules/mesh-task/templates/consul_client_command.tpl

This corrects the `-type aws` option to `-type aws-iam`. The `consul login` command actually [ignores](https://github.com/hashicorp/consul/blob/8712a088b18b798a53d3b9792291ef23cec4f750/command/login/login.go#L33) the `-type` flag, but we should correct this anyway on our side.
👀 

Correct login type

---

CHANGELOG.md
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/basic/terraform/service-name-validate/main.tf

Enforce lower case service names to match https://github.com/hashicorp/consul-ecs/pull/97
mesh-task does the following:
- `var.consul_service_name` is validated to be a [valid service identity](https://github.com/hashicorp/consul/blob/93b164aac37f83863707f05284b868dc8ea57719/acl/validation.go#L11)
- If the consul_server_name is not provided, fall back to the lowercase task family name
👀 

Enforce lowercase service names

---

examples/admin-partitions/terraform/aws_ecs.tf
examples/admin-partitions/terraform/client.tf
examples/admin-partitions/terraform/server.tf

This ensures the admin-partitions example uses lower case service names.
Ran the example locally
👀

Ensure lowercase service name in AP example

---

CHANGELOG.md
modules/gateway-task/main.tf

When ACLs are enabled gateway tasks do a `consul login` to get a token using the IAM Auth Method. The ACL controller will delete the tokens during its reconciliation cycle but we want task to do a `consul logout` when it stops to destroy the tokens. This PR adds a `health-sync` container to the gateway-task so that the task automatically attempts a `consul logout` when the task stops.
- Ran the updated gateway-task and confirmed that health-sync performs the `consul logout`:
```log
2022-06-15T18:50:34.380Z [INFO]  signal received, ignoring: signal=terminated
2022-06-15T18:50:34.380Z [INFO]  log out token: file=/consul/service-token
2022-06-15T18:50:34.387Z [INFO]  log out token: file=/consul/client-token
```
:eyes: (Suggest ignoring whitespace to skip the indenting changes)

Add health-sync to gateway-tasks when ACLs are enabled

---

CHANGELOG.md
examples/mesh-gateways/datacenters.tf
examples/mesh-gateways/gateway/gateway.tf
examples/mesh-gateways/gateway/outputs.tf
examples/mesh-gateways/outputs.tf
modules/gateway-task/config.tf
modules/gateway-task/main.tf
modules/gateway-task/outputs.tf
modules/gateway-task/validation.tf
modules/gateway-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/mesh-gateway-validate/main.tf

- Add an optional configuration to have the `gateway-task` module automatically create and configure a Network Load Balancer for public ingress.
- Update the `gateway-task` module to create the ECS service definition.
- Unit tests
- Tested against the mesh-gateway example
:eyes:

Add load balancer and ECS service to gateway-task

---

.circleci/config.yml
test/acceptance/setup-terraform/hcp/main.tf
test/acceptance/setup-terraform/hcp/outputs.tf
test/acceptance/setup-terraform/hcp/variables.tf
test/acceptance/setup-terraform/main.tf
test/acceptance/setup-terraform/outputs.tf
test/acceptance/setup-terraform/variables.tf
test/acceptance/tests/hcp/hcp_test.go

This updates CI and acceptance tests to skip the HCP tests on PRs.
The way this works is:
* Pass either `-var enable_hcp=true|false` to setup-terraform to control whether an HCP Consul cluster is created.
* HCP tests look for the `enable_hcp` output variable in setup-terraform, and skip themselves if there is no HCP cluster.
* In CI, we set `enable_hcp=true` for `main` and `release/*` branches. Otherwise, it is set to false.
For the moment, no enterprise tests will run on PRs, which I'll address in a follow up using the dev-server.
👀 

Skip HCP tests on PRs

---

test/acceptance/framework/config/config.go
test/acceptance/framework/helpers/cloudwatch.go
test/acceptance/framework/helpers/helpers.go
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf

This updates TestBasic to run the `secure:true` and `secure:false` cases in parallel.
Right now, this only saves about 5 mins (~15 mins vs 20mins). More importantly, it enables us to add additional tests for enterprise dev-server without extending the test runtime (hopefully).
👀 

Parallelize TestBasic

---

.circleci/config.yml
test/acceptance/README.md
test/acceptance/framework/config/config.go
test/acceptance/framework/flags/flags.go
test/acceptance/setup-terraform/hcp/main.tf
test/acceptance/setup-terraform/main.tf
test/acceptance/setup-terraform/outputs.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/hcp_test.go
test/acceptance/tests/hcp/terraform/ap/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/main.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

This adds an enterprise test to TestBasic. Right now, it doesn't do anything special with partitions or namespaces.
I updated things to pass a _list_ of ECS clusters from setup-terraform through to test cases and (usually) through to Terraform. This fixes an issue I caused where the ECS cluster wasn't being passed correctly in HCP tests, and I fixed an issue with parallel `terraform init`s in TestBasic
- Acceptance tests in CI, and locally
👀 

Add initial enterprise dev-server test

---

test/acceptance/tests/hcp/hcp_test.go

- Fixes to HCP to use ClusterARN slices within validation test. 
- Ran acceptance test locally
👀 

Fixes to HCP test

---

CHANGELOG.md
modules/dev-server/main.tf

Fix a bug in the `dev-server` where it doesn't pick up the correct secret ARN for the gossip encryption key when the module is configured to generate the gossip key. When `var.gossip_encryption_enabled = true` the module is supposed to create and use a gossip key. However, when `gossip_encryption_enabled = true` it was always using the value of `var.gossip_key_secret_arn`, even if that was unset (which it should be in the case where the key is generated). This caused the creation of the execution role policy to fail because the `Resource` ARN for gossip key secret was the empty string.
- :eyes:
- Using the Lambda registrator acceptance tests (how I found the issue)
:eyes:
[Changelog entries should use present …

Fix gossip key ARN

---

.circleci/config.yml
modules/dev-server/main.tf
test/acceptance/framework/helpers/helpers.go
test/acceptance/go.mod
test/acceptance/go.sum
test/docker/Makefile
test/docker/README.md
test/docker/Test.dockerfile

- Bump acceptance tests to Go 1.19
- Bump Terraform to 1.3.4
- Update other versions (gotestsum, golangci-lint, aws cli, session-manager-plugin)
- Don't use `grpc_tls` setting yet, which is not valid in 1.13.3
* Acceptance test locally with both Consul 1.12.2 and 1.13.3

Update test dependencies

---

.circleci/config.yml
CHANGELOG.md
modules/mesh-task/config.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/basic/terraform/public-listener-port-validate/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

This backports https://github.com/hashicorp/terraform-aws-consul-ecs/pull/142 to release/0.5.x

Backport: Add envoy_public_listener_port input var to mesh-task [0.5.x]

---

.circleci/config.yml
CHANGELOG.md
LICENSE
modules/dev-server/consul_1_14_compat.tf
modules/dev-server/main.tf
modules/dev-server/variables.tf
modules/gateway-task/templates/consul_agent_defaults.hcl.tpl
modules/gateway-task/validation.tf
modules/mesh-task/templates/consul_agent_defaults.hcl.tpl
test/acceptance/framework/config/config.go
test/acceptance/framework/helpers/cloudwatch.go
test/acceptance/framework/helpers/helpers.go
test/acceptance/go.mod
test/acceptance/go.sum
test/acceptance/setup-terraform/hcp/main.tf
test/acceptance/setup-terraform/hcp/variables.tf
test/acceptance/setup-terraform/main.tf
test/acceptance/setup-terraform/outputs.tf
test/acceptance/setup-terraform/variables.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/hcp/hcp_test.go
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/docker/Makefile
test/docker/README.md
test/docker/Test.dockerfile

This backports the following to the 0.5.x release branch:
* #140 - To fix a bounds check in test helpers
* #141 - To update test dependencies (including Go 1.19) and improve test logging
* #146 - To test with Consul 1.13 and 1.14
* #138 - To remove the `telemetry.disable_compat_1.9` to support 1.13+, and support cluster peering (1.14+ only)
* #137 - To sync the license copyright to the release branch
👀 

Backport: Test with 1.13 and 1.14 to release/0.5.x

---

.circleci/config.yml
CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/mesh-gateways/datacenter/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
modules/acl-controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

* Bump default [Envoy image to 1.21.6](https://hub.docker.com/r/envoyproxy/envoy-alpine/tags)
* Bump default Consul image to 1.12.7
* Bump versions of Consul in acceptance tests to 1.12.7, 1.13.4, and 1.14.2 which are the latest available in HCP
* Set the TF module version to 0.5.2
* Bump default Consul ECS image to 0.5.2
* CI tests

Prep for 0.5.2

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
modules/acl-controller/variables.tf
modules/dev-server/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

* Bump default Consul version to 1.11.11
* Bump default Envoy version to 1.20.7
* Set TF module version to 0.4.3
* Bump consul-ecs version to 0.4.3
* Update changelog
CI tests

Prep for 0.4.3

---

CHANGELOG.md
modules/acl-controller/main.tf
modules/acl-controller/variables.tf

Refers to https://github.com/hashicorp/terraform-aws-consul-ecs/issues/150
- Add variable `additional_execution_role_policies` to `acl-controller` module
- Local environment:

Add support for additional_execution_role_policies  in acl-controller

---

CHANGELOG.md
modules/acl-controller/main.tf

- ACL controller: only grant read-only access to root file system. To avoid trigger the following AWS Security Hub alert:
> [ECS.5] This control checks if ECS containers are limited to read-only access to mounted root filesystems. This control fails if the ReadonlyRootFilesystem parameter in the container definition of ECS task definitions is set to ‘false’. [Remediation instructions](https://docs.aws.amazon.com/console/securityhub/ECS.5/remediation)
https://github.com/hashicorp/terraform-aws-consul-ecs/issues/157
- Locally bootstrap the ACL controler with this change and no side effect was detected.

Only grant read-only access to root file system.

---

CHANGELOG.md
modules/mesh-task/main.tf

- Exclude task_def from `defaulted_check_containers` if the `healthCheck` property is present but its null. https://github.com/hashicorp/terraform-aws-consul-ecs/pull/153
- Locally.
Not ideal but this can be tested with this snippet:
```hcl
locals {
container_defs_with_depends_on = [{
name        = "x"
essential   = true
healthCheck = null
},
{
name      = "y"
essential = true
healthCheck = {
command = ""
}
},
{
name      = "z"
essential = true
}
]
defaulted_check_containers_before = [for def in local.container_defs_with_depends_on : def.name
if contains(keys(def), "essential") && contains(keys(def), "healthCheck")]
defaulted_check_containers_now = [for def in local.container_defs_with_depends_on : def.name
if contains(keys(def), "essential") && contains(keys(def), "healthCheck") && …
```

Improve the logic behind the 'defaulted_check_containers' local creation

---

.circleci/config.yml
CHANGELOG.md
modules/gateway-task/main.tf
modules/gateway-task/templates/consul_client_command.tpl
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/templates/consul_client_command.tpl
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf

This PR adds support for:
- Acceptance testing with the latest N-2 Consul versions (Currently, 1.15.0, 1.14.4, and 1.13.6)
- Using the Consul HTTP API to read the client ACL token after performing the `consul login` using the AWS auth method. There is an [issue with using the `consul acl token read -self` on Consul 1.15.0](https://github.com/hashicorp/consul/pull/16445), so `mesh-task` and `gateway-task` have been updated to use the HTTP API instead.
- Bumps the Envoy version to v1.23.1 and switches to distroless
- Uses the new `consul-ecs net-dial` command for ECS health checks on the `sidecar-proxy` container.
- Acceptance tests
:eyes: 

Add support for Consul 1.15.x

---

.circleci/config.yml

HCP Consul does not currently have support for Consul 1.15.x nor the latest Consul patch releases for 1.14.x and 1.13.x. This PR:
- Binds the non-HCP tests to the **latest** Consul 1.15, 1.14 and 1.13 patch releases
- Binds the HCP tests to the **supported** Consul 1.14 and 1.13 patch releases
- Adds a TODO to update HCP Consul for 1.15.x when it is available
:eyes: 

Use supported HCP Consul versions in Acceptance Tests

---

CHANGELOG.md
modules/gateway-task/main.tf

Use the `consul-ecs envoy-entrypoint` to run and monitor the `envoy` process in `gateway-tasks`. This change bings the gateway task inline with how `mesh-task` starts Envoy and ensures that Envoy is correctly started and monitored.
Local Lambda acceptance tests
:eyes:

Use `consul-ecs envoy-entrypoint` to start Envoy for gateway-tasks

---

CHANGELOG.md
modules/acl-controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

This PR updates the Consul on ECS Terraform modules to use `consul-ecs v0.6.0` and the latest 1.15.1 patch release of Consul.
Acceptance tests :heavy_check_mark: 
:eyes: 

Consul ECS 0.6.0 release

---

.github/workflows/terraform-ci.yml

This PR specifies the path to the `go.sum` file in the `test/acceptance` directory so that the `setup-go` action can successfully find the cache dependency file.
Acceptance tests in CI
:eyes: 

Update cache file for setup-go action

---

.github/workflows/terraform-ci.yml
test/acceptance/setup-terraform/main.tf

- Bump the vpc module to `5.0.0` because the existing version was failing with some unknown input variable related error.
- Bump consul to the latest patch versions for each minor version release.
- For some reason, the default vpc did not contain security group rules for egress and ingress traffic. Added rules to cover the same

Fix acceptance tests

---

test/acceptance/setup-terraform/main.tf

- Fixes the existing ingress security group rule for the VPC that gets created for the acceptance tests. Doing so prevents public internet traffic from reaching this vpc network.
CI

Fix ingress security group rule

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf

- Bump Consul images to it's latest patch release
- Bump Envoy image to the image supported by dataplane 1.2.0

Bump consul and envoy versions

---

examples/admin-partitions/terraform/client.tf
examples/admin-partitions/terraform/server.tf
examples/cluster-peering/client-app.tf
examples/cluster-peering/server-app.tf
examples/dev-server-ec2/README.md
examples/dev-server-ec2/main.tf
examples/dev-server-ec2/variables.tf
examples/dev-server-fargate/main.tf
examples/mesh-gateways/client-app.tf
examples/mesh-gateways/server-app.tf
examples/service-sameness/client-app/client.tf
examples/service-sameness/server-app/server-app.tf
modules/mesh-task/config.tf
modules/mesh-task/main.tf
modules/mesh-task/validation.tf
modules/mesh-task/variables.tf
test/acceptance/tests/validation/terraform/tproxy-ec2-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Modified mesh-task submodule to support TProxy. The following are the changes
- Added a `enable_transparent_proxy` input that defaults to `true`
- Adds individual variables to support multiple parts of the `transparentProxy` config.
- Modified existing examples to support tproxy.
Manual deployment
👀 

Changes to support TProxy for ECS EC2

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Bump ECS image variables to refer to the latest release candidate's name
- Split existing acceptance test matrix into Fargate and EC2 to reduce flakiness
CI
👁️ 

Reference ECS release candidate images for examples and submodules

---

modules/gateway-task/main.tf
modules/gateway-task/variables.tf
test/acceptance/tests/validation/terraform/mesh-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Makes the count of gateway ECS tasks configurable, to enable more than one load balanced gateways.

Expose `gateway_count` in gateway module

---

.github/workflows/reusable-ecs-acceptance.yml
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Modify images to point to the release candidate images. This is needed to release 0.7.0-rc1 of the terraform-aws-consul-ecs submodules.
CI, Manual
👀 

Point terraform modules to use latest Consul images

---

CHANGELOG.md
modules/gateway-task/main.tf
modules/mesh-task/main.tf

Prep release 0.7.x

---

.github/workflows/terraform-ci.yml

- Fix Consul version for HCP and non HCP setups. This is being done because `1.17.0` isn't yet available on HCP

Fix Consul version in CI

---

modules/gateway-task/iam.tf

- Changes the condition in the IAM execution policy on whether the `"secretsmanager:GetSecretValue"` statement is added to the existence of the `var.consul_ca_cert_arn`.   This makes it so that TLS can be enabled without passing that value and uses the logic used for the other statements in that IAM policy.
-

Change IAM execution policy condition to require consul_ca_cert_arn instead of tls

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
CHANGELOG.md
modules/gateway-task/iam.tf
modules/gateway-task/main.tf
modules/gateway-task/validation.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/validation/terraform/api-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Adds changes to the `gateway-task` submodule to support configuring API gateways on ECS.
- Adds `consul.hashicorp.com.gateway-kind` as a tag to the gateway task's IAM Role. This field will hold the type of the gateway that is getting deployed to the ECS task and will be used by the configured IAM auth method to mint tokens
- Update CI to test against Consul 1.17
- Adds a `custom_lb_config` input to the gateway-task submodule to ease configuration of LBs for API GWs
Manually deploying API GWs on ECS

Update gateway submodule to support API gateways

---

CHANGELOG.md
modules/gateway-task/variables.tf
test/acceptance/tests/validation/terraform/terminating-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Add `terminating-gateway` as an acceptable kind input for the gateway submodule
- Add validation tests to cover the same.
CI

Add basic validation to support TGWs

---

examples/api-gateway/controller.tf
examples/api-gateway/echo-service/variables.tf
examples/api-gateway/gateway.tf
test/acceptance/framework/config/config.go
test/acceptance/framework/flags/flags.go
test/acceptance/setup-terraform/outputs.tf
test/acceptance/tests/basic/basic_test.go
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/main.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/main.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- A majority of our tests in the ECS acceptance test suite are flaky. Upon investigation, it was found that a majority of these failures are linked to the scenario where ECS mesh tasks are unable to reach the Consul server. The main reason for this is that we deploy both the server and individual mesh tasks in parallel with terraform and servers generally take a bit of time before their CloudMap DNS name gets resolved to a private IP.
This PR adds two changes to fix this issue
- Associate the server with an ALB and query `/v1/catalog/services` for its readiness
- Make sure that the ECS controller and other application task submodules depend on the server module's completion. This will ensure that the client workload tasks only get deployed after the server's ECS service and task are up …

Effort to reduce flakiness in ECS acceptance tests

---

CHANGELOG.md
modules/gateway-task/main.tf
modules/mesh-task/main.tf

- The ECS health check logic relies on the command returning a non zero exit code. In the current state, even when `consul-ecs-control-plane` returns back a `500` the `curl` command treats it a successful response and returns a non zero code. Here's an example of the same
```zsh
ganeshseetharaman@ganeshseetharaman-DFCQN60JDW % curl -v httpbin.org/status/500 
*   Trying 3.95.102.170:80...
* Connected to httpbin.org (3.95.102.170) port 80 (#0)
> GET /status/500 HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Date: Fri, 15 Dec 2023 08:26:54 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< …
```

Fix health check command for mesh and gateway task submodules

---

examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Make changes to Consul ECS images to use the `0.7.1` preview image.
CI

Remove dev tag from  Consul ECS image version

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/datacenter/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Bump Consul ECS image versions to 0.7.1
- Bump Dataplane image version to reflect the latest patch release - 1.3.1
- Update CHANGELOG
CI

Prep 0.7.1 release

---

.github/workflows/nightly-ecs-examples-validator.yml
.github/workflows/reusable-ecs-example-validator.yml
examples/dev-server-fargate/main.tf
examples/locality-aware-routing/README.md
examples/locality-aware-routing/outputs.tf
test/acceptance/README.md
test/acceptance/examples/README.md
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/cluster-peering/main.go
test/acceptance/examples/scenarios/common/common.go
test/acceptance/examples/scenarios/common/consul.go
test/acceptance/examples/scenarios/common/ecs.go
test/acceptance/examples/scenarios/common/fake_service.go
test/acceptance/examples/scenarios/common/fake_service_test.go
test/acceptance/examples/scenarios/ec2/main.go
test/acceptance/examples/scenarios/fargate/main.go
test/acceptance/examples/scenarios/hcp/main.go
test/acceptance/examples/scenarios/locality-aware-routing/main.go
test/acceptance/examples/scenarios/registry.go
test/acceptance/examples/scenarios/registry_test.go
test/acceptance/examples/scenarios/scenario.go
test/acceptance/examples/scenarios/service-sameness/main.go
test/acceptance/examples/scenarios/wan-federation/main.go

TLDR~ Framework to ease examples validation present in this repository.
**Background**
1. Each time a new release goes out for Consul ECS, we rely on the acceptance tests present in this repository to determine the health of the new release. Acceptance tests only provide limited test coverage and doesn't test much of server oriented features like peering, wan federation, sameness etc.
2. We have a started adding lot of examples that help users deploy multiple Consul features on ECS. We currently don't have a way to check if something broke in an automated fashion. Someone has to manually run these example terraform configs to determine if an E2E setup is healthy or not. The same issue occurs when we release a new version of Consul ECS. We don't have a way to perform automated sanity tests …

Validation framework for terraform examples

---

test/acceptance/examples/scenarios/service-sameness/main.go

- Fixes a small bug that caused the sameness group validation to fail in https://github.com/hashicorp/terraform-aws-consul-ecs/actions/runs/7275194658

Fix sameness group validation bug

---

CHANGELOG.md
README.md
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf

- Adds the `consul-ecs-health-sync` container to the mesh-task and gateway-task task definitions.
- Adds changes to the README to reflect the same.
- Needed to support https://github.com/hashicorp/consul-ecs/pull/211

Changes to add health-sync container to the task definition

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/reusable-ecs-example-validator.yml

- Reverts https://github.com/hashicorp/terraform-aws-consul-ecs/pull/254
- The new version prevents uploading artifacts with same names from different job basically preventing us from running concurrent jobs. Since there is no business need to  upgrade to the new version, I am downgrading it back to the older version

Downgrade upload-artifact action

---

.github/CODEOWNERS
.github/workflows/nightly-ecs-examples-validator.yml
.github/workflows/reusable-ecs-example-validator.yml
examples/dev-server-fargate/main.tf
examples/locality-aware-routing/README.md
examples/locality-aware-routing/outputs.tf
test/acceptance/README.md
test/acceptance/examples/README.md
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/cluster-peering/main.go
test/acceptance/examples/scenarios/common/common.go
test/acceptance/examples/scenarios/common/consul.go
test/acceptance/examples/scenarios/common/ecs.go
test/acceptance/examples/scenarios/common/fake_service.go
test/acceptance/examples/scenarios/common/fake_service_test.go
test/acceptance/examples/scenarios/ec2/main.go
test/acceptance/examples/scenarios/fargate/main.go
test/acceptance/examples/scenarios/hcp/main.go
test/acceptance/examples/scenarios/locality-aware-routing/main.go
test/acceptance/examples/scenarios/registry.go
test/acceptance/examples/scenarios/registry_test.go
test/acceptance/examples/scenarios/scenario.go
test/acceptance/examples/scenarios/service-sameness/main.go
test/acceptance/examples/scenarios/wan-federation/main.go

- Manual backport of https://github.com/hashicorp/terraform-aws-consul-ecs/pull/250 

[Backport-0.7.x] Validation framework for terraform examples (#250)

---

CHANGELOG.md
modules/gateway-task/main.tf
modules/mesh-task/main.tf

- Improve bootstrap time for mesh/gateway task containers by reducing health check interval
- Fixes https://github.com/hashicorp/terraform-aws-consul-ecs/issues/257

Reduce health check interval to improve bootstrap time

---

CHANGELOG.md
modules/gateway-task/iam.tf

- This is needed to support https://github.com/hashicorp/consul-ecs/pull/216. Consul will look for this tag and use it as a selector to selectively mint tokens/resolve binding rules for specific gateways
Manual deployment

Add `consul.hashicorp.com.gateway-kind` to gateway-task's IAM role

---

examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Update `consul-ecs` images to point to the latest dev patch version. This is a prerequisite to run acceptance/scenario tests on the `release/0.7.x` branch.

Bump consul-ecs to use the latest dev version

---

.github/workflows/nightly-ecs-examples-validator.yml
.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/reusable-ecs-example-validator.yml
.github/workflows/reusable-get-go-version.yml
.github/workflows/reusable-go-fmt-and-lint.yml
.github/workflows/reusable-terraform-fmt.yml
.github/workflows/scenario-validator.yml
.github/workflows/terraform-ci.yml

- Adds a workflow that runs scenario tests for a given scenario.

Add scenario validator

---

CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

* Bump Consul ECS image version to 0.7.2
* Bump Consul Dataplane's image version to 1.3.2
* Bump Consul image version to 1.17.2

Prepare 0.7.2 release

---

CHANGELOG.md

Consolidate changelog for 0.7.2

---

CHANGELOG.md
modules/gateway-task/config.tf
modules/gateway-task/main.tf
modules/gateway-task/validation.tf
modules/gateway-task/variables.tf
test/acceptance/tests/validation/terraform/api-gateway-validate/main.tf
test/acceptance/tests/validation/terraform/mesh-gateway-validate/main.tf
test/acceptance/tests/validation/terraform/terminating-gateway-validate/main.tf
test/acceptance/tests/validation/terraform/tproxy-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Adds support for configuring TProxy for gateway-task submodule.
CI

Support TProxy for gateway-task submodule

---

examples/terminating-gateway-tls/client.tf
examples/terminating-gateway-tls/gateway.tf

- Adds `enable_transparent_proxy` as `false` for fargate based tasks inside the term-gtw with tls example

Fix broken terminating-gtws with tls example

---

.github/workflows/terraform-ci.yml
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/datacenter/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf
test/acceptance/tests/tproxy/terraform/main.tf

- Update `consul-ecs` to point to the `preview` version of `0.8.0-rc1`
- Update `consul` and `consul-dataplane` to point to their corresponding RC release versions

Prep 0.8.0-rc1 release

---

.github/workflows/reusable-ecs-acceptance.yml
.github/workflows/terraform-ci.yml
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/datacenter/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Update Consul and Consul dataplane to their latest patch versions
- Update Consul-ECS to 0.7.3 preview image

Prep 0.7.3 dev release

---

.github/workflows/terraform-ci.yml
CHANGELOG.md
examples/admin-partitions/terraform/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
modules/acl-controller/variables.tf
modules/gateway-task/main.tf
modules/gateway-task/variables.tf
modules/mesh-task/main.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf

- Use `hashicorp/consul-ecs:0.6.2` for the 0.6.2 TF module

Prep prod release 0.6.2

---

.github/workflows/nightly-ecs-examples-validator.yml
examples/terminating-gateway-tls/client.tf
test/acceptance/examples/main_test.go
test/acceptance/examples/scenarios/terminating-gateway-tls/main.go
test/acceptance/tests/validation/terraform/volume-variable-gateway-validate/main.tf
test/acceptance/tests/validation/validation_test.go

- Adds a scenario test for testing terminating gateways with TLS.
- Adds a validation test for testing usage of volume variables with gateways
- Adds the scenario test as part of the nightly ECS example validation workflow
CI

Add scenario test for testing terminating gateways with TLS

---

modules/gateway-task/main.tf
modules/gateway-task/variables.tf

- add new variable `extra_container_definitions`
- Merge these definitions in with the rest of the container_definitions
- This allows users to add extras like sidecars for monitoring/metrics/logging/tracing etc.
Deployed with the same pattern from mesh-task module.
deploy a test terminating gateway with a sidecar.
- [ NA ] Tests added

Add additional container definitions option to gateway-task submoddule

---

CHANGELOG.md
examples/admin-partitions/terraform/hcp_consul.tf
examples/admin-partitions/terraform/variables.tf
examples/cluster-peering/gateway/variables.tf
examples/cluster-peering/variables.tf
examples/locality-aware-routing/variables.tf
examples/mesh-gateways/gateway/variables.tf
examples/mesh-gateways/variables.tf
examples/service-sameness/datacenter/variables.tf
examples/service-sameness/gateway/variables.tf
examples/service-sameness/variables.tf
examples/terminating-gateway-tls/variables.tf
modules/controller/variables.tf
modules/dev-server/variables.tf
modules/gateway-task/variables.tf
modules/mesh-task/variables.tf
test/acceptance/tests/basic/terraform/basic-install/main.tf
test/acceptance/tests/hcp/terraform/ap-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ap/variables.tf
test/acceptance/tests/hcp/terraform/hcp-install/variables.tf
test/acceptance/tests/hcp/terraform/ns-tproxy/variables.tf
test/acceptance/tests/hcp/terraform/ns/variables.tf
test/acceptance/tests/tproxy/terraform/main.tf

- Updating the changelog based on the 0.8.1 release
- `main` development is stale compared to`release/0.8.x` - I opted to set the appropriate dev versions in main in advance of a 0.9.0 release, rather than trying to port the changes from `release/0.8.x` and perform another update. The 0.9.0 release it outside the immediate scope of this work.

Post release 0.8.1
